import Instar.TwoLevelFinal.SyntacticSoundness.PresvSubst
import Instar.TwoLevelFinal.SyntacticSoundness.PresvMaping
import Instar.TwoLevelFinal.SyntacticSoundness.PresvCtx
import Instar.TwoLevelFinal.SyntacticSoundness.PresvPure
import Instar.TwoLevelFinal.SyntacticSoundness.PresvMut
import Instar.TwoLevelFinal.SyntacticSoundness.PresvReflect
import Instar.TwoLevelFinal.SyntacticSoundness.Preservation
import Instar.TwoLevelFinal.SyntacticSoundness.Progress
