import Instar.TwoLevelMut.OperationalSemantics.Value
import Instar.TwoLevelMut.OperationalSemantics.Store
import Instar.TwoLevelMut.OperationalSemantics.EvalCtx
import Instar.TwoLevelMut.OperationalSemantics.SmallStep
import Instar.TwoLevelMut.OperationalSemantics.Congruence
import Instar.TwoLevelMut.OperationalSemantics.Deterministic
import Instar.TwoLevelMut.OperationalSemantics.Confluence
