name = "instar-mechanization"
version = "0.1.0"
defaultTargets = ["instar-mechanization"]

[[lean_lib]]
name = "Instar"

[[lean_exe]]
name = "instar-mechanization"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"