import Instar.TwoLevelBasic.SyntacticSoundness.PresvSubst
import Instar.TwoLevelBasic.SyntacticSoundness.PresvMaping
import Instar.TwoLevelBasic.SyntacticSoundness.PresvCtx
import Instar.TwoLevelBasic.SyntacticSoundness.PresvPure
import Instar.TwoLevelBasic.SyntacticSoundness.PresvReflect
import Instar.TwoLevelBasic.SyntacticSoundness.Preservation
import Instar.TwoLevelBasic.SyntacticSoundness.Progress
import Instar.TwoLevelBasic.SyntacticSoundness.Soundness
