import Instar.TwoLevelRec.SyntacticSoundness.PresvSubst
import Instar.TwoLevelRec.SyntacticSoundness.PresvMaping
import Instar.TwoLevelRec.SyntacticSoundness.PresvCtx
import Instar.TwoLevelRec.SyntacticSoundness.PresvPure
import Instar.TwoLevelRec.SyntacticSoundness.PresvReflect
import Instar.TwoLevelRec.SyntacticSoundness.Preservation
import Instar.TwoLevelRec.SyntacticSoundness.Progress
import Instar.TwoLevelRec.SyntacticSoundness.Soundness
