import Instar.TwoLevelBasic.OperationalSemantics.Value
import Instar.TwoLevelBasic.OperationalSemantics.EvalCtx
import Instar.TwoLevelBasic.OperationalSemantics.SmallStep
import Instar.TwoLevelBasic.OperationalSemantics.Congruence
import Instar.TwoLevelBasic.OperationalSemantics.Deterministic
import Instar.TwoLevelBasic.OperationalSemantics.Confluence
