import Instar.TwoLevelRec.OperationalSemantics.Value
import Instar.TwoLevelRec.OperationalSemantics.EvalCtx
import Instar.TwoLevelRec.OperationalSemantics.SmallStep
import Instar.TwoLevelRec.OperationalSemantics.Congruence
import Instar.TwoLevelRec.OperationalSemantics.Deterministic
import Instar.TwoLevelRec.OperationalSemantics.Confluence
import Instar.TwoLevelRec.OperationalSemantics.Refine
import Instar.TwoLevelRec.OperationalSemantics.Termination
