import Instar.TwoLevelFinal.SyntacticTyping.Effect
import Instar.TwoLevelFinal.SyntacticTyping.Ty
import Instar.TwoLevelFinal.SyntacticTyping.Env
import Instar.TwoLevelFinal.SyntacticTyping.Typing
import Instar.TwoLevelFinal.SyntacticTyping.Weakening
import Instar.TwoLevelFinal.SyntacticTyping.Shrinking
import Instar.TwoLevelFinal.SyntacticTyping.EraseSafety
